### ISSUE TITLE
검색 결과가 없는 검색어에 대한 예외 처리

### ISSUE THREAD

**Issue by februa22** [februa22/naver-shopping#3]
검색 결과가 없는 인기검색어가 존재한다.

검색어 `수비진융기모`

- 카테고리: 청바지
- 인기검색어 순위: 33

에러 메시지:

```python
Traceback (most recent call last):
  File "C:\Users\22feb\Miniconda3\envs\naver\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\22feb\Miniconda3\envs\naver\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\22feb\dev\workspace\naver-shopping\popularity\popularity.py", line 192, in <module>
    main()
  File "C:\Users\22feb\dev\workspace\naver-shopping\popularity\popularity.py", line 125, in main
    num_productset = get_num_productset(html)
  File "C:\Users\22feb\dev\workspace\naver-shopping\popularity\popularity.py", line 92, in get_num_productset
    productset = productset_soup.text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by februa22** [comment]
예외 처리 완료.
